---
- name: Config SonarQube Server Example using API and uri/curl
  hosts: all
  connection: local
  vars:
    sonar_api_url: "https://yoursonarqubeserver.com/api"
    sonar_token: "YourSonarQubeApiTokenThatRequiresAdminRights"
    sonar_password: ""
    sonar_profile: "YourSonarQubeProfileToLoad.xml"
  tasks:
    - name: Force User Authentication
      uri:
        url: "{{ sonar_api_url }}/settings/set"
        method: POST
        status_code: 204
        body: "key=sonar.forceAuthentication&value=true"
        force_basic_auth: yes
        user: "{{ sonar_token }}"
        password: "{{ sonar_password }}"
        validate_certs: no
    - name: POST a SonarQube Profile xml via curl
      shell: 'curl  -X "POST" "{{ api_url }}/qualityprofiles/restore" \
                    -H "Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__" \
                    -u {{ username }}: \
                    -k \
                    --form backup=@{{ sonar_profile }}'